### PR TITLE
Feature/erlzmq hex and fix decimal erlang 20

### PR DESCRIPTION
**Pull request by ghost**
upgraded/fixed version of erlzmq (rebar3) from hex and upgraded decimal to 1.7.0 (and added override) in order to fix build on erl 20/elixir 1.8.2

### CODE REVIEW

**Comment by ghost** [comment]
Yeah - the erlzmq2 package was doing some really unpleasant things like downloading an ancient version of the zmq source code as part of it's build, relied on a Makefile, relied on the old rebar, had problems building IElixir and just decided to pull the whole thing apart.

**Comment by ghost** [comment]
Coveralls report is incorrect - I don't know how coverage could have decreased - I haven't modified any of the source code - just changed a dependency and updated the README.

**Comment by ghost** [comment]
You like ?

**Comment by pprzetacznik** [comment]
@bryanhuntesl thanks for you input. Do you know exactly why decimal override is necessary here?

**Comment by pprzetacznik** [comment]
@bryanhuntesl I see there were problem with Boyle's test that can be fixed with adding `app: false` to in that test. Do you see any else issue with decimal?

**Comment by ghost** [comment]
> @bryanhuntesl I see there were problem with Boyle's test that can be fixed with adding `app: false` to in that test. Do you see any else issue with decimal?

Setting app: false should be sufficient thanks @pprzetacznik - I was thinking of upgrading SQLite to ecto 3 next - would you be interested in a pr for that?

**Comment by ghost** [comment]
Thanks @pprzetacznik

**Comment by pprzetacznik** [comment]
I was looking for a bug on a branch commit, it took me a while. Now your changes are again on master. I've also upgraded sqlite to ecto 3.

Thanks for your input!

**Comment by ghost** [comment]
> I was looking for a bug on a branch commit, it took me a while. Now your changes are again on master. I've also upgraded sqlite to ecto 3.
> 
> Thanks for your input!

Excellent. My pleasure.

**Pull request merged**
