### PR TITLE
Allow notebook to resolve starting working directory

### PR DESCRIPTION
**Pull request by Virviil**
## The problem

When the notebook is started, we sometimes need to import files or modules from relative paths from the file. For example:

```
c "my_helper_module.ex"

# or

Jason.decode!(File.read!("../data.json")
```

In order to do this, **jupyter** can be started from the relevant folder. In elixir, we can check the folder name using 
```
iex> cwd
#or
iex> File.cwd
```

This PR allows kernel to resolve the current working directory properly.

### CODE REVIEW

**Comment by pprzetacznik** [comment]
@Virviil, this is really cool. Could you please also add a small note to the README.md file about this?

**Comment by Virviil** [comment]
@pprzetacznik I've added notebook-as-example because no need to add this to the readme - it's common behavior for all the other kernels. Can you please check out the failing CI?

**Comment by Virviil** [comment]
@pprzetacznik CI is fixed 👍

**Comment by pprzetacznik** [comment]
Thanks! :)

**Pull request merged**
